server:
  port: 7072

spring:
  application:
    name: interlude-auth
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/interlude_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: 77871219
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 3000ms

project:
  folder: F:/webser/interlude/

gateway:
  auth:
    secret: interlude-gateway-local-secret

mybatis:
  configuration:
    map-underscore-to-camel-case: true
