server:
  port: 7071
#  servlet:
#    context-path: /admin
spring:
  elasticsearch:
    uris: http://127.0.0.1:9200
  ai:
    openai:
      api-key: sk-7f02f83c000b4e89b5b103cf8ce49716
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  application:
    name: interlude-web
  # mail:
  #   host: smtp.qq.com
  #   port: 587
  #   username: your_email@example.com
  #   password: your_mail_auth_code
  #   properties:
  #     mail:
  #       smtp:
  #         auth: true
  #         starttls:
  #           enable: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/interlude_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: 77871219
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 3000ms
      jedis:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
#mybatis 大小写转驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true

project:
  folder: F:/webser/interlude/
log:
  root:
    level: info

debug: false

logging:
  level:
    org.springframework.boot.autoconfigure.condition: error
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: off
